In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])

In [6]:
array1

array([[10,  8],
       [ 3,  5]])

In [11]:
A = np.linalg.inv(array1)
A

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [12]:
A @ array1

array([[1., 0.],
       [0., 1.]])

In [ ]:
#是，單位矩陣

In [13]:
w, v = np.linalg.eig(array1)

In [14]:
w

array([13.,  2.])

In [15]:
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [17]:
u, s, vh = np.linalg.svd(array1)

In [18]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [19]:
s

array([13.94721714,  1.86417116])

In [20]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])